mysiteS171/myapp/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
        url(r'^$', views.IndexView, name='index'),
        url(r'^index0/$', views.IndexView, name='index'),
        url(r'^about/$', views.about, name='about'),
        url(r'^(?P<course_no>\d+)/$', views.CourseDetailView, name='detail'),
        url(r'^topics/$', views.topics, name='topics'),
        url(r'^addtopic/$', views.addtopic, name='addtopic'),
        url(r'^topics/(?P<topic_id>\d+)/$', views.topicdetail, name='topicdetail'),
        url(r'^register/$', views.register, name='register'),
        url(r'^login/$', views.user_login, name='login'),
        url(r'^logout/$', views.user_logout, name='logout'),
        url(r'^mycourses/$', views.mycourses, name='mycourses'),
]

mysiteS171/mysiteS171/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^myapp/', include('myapp.urls', namespace='myapp')),
]

mysiteS171/myapp/models.py
from django.db import models
from datetime import datetime
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _
# Create your models here.

class Author(models.Model):
    firstname = models.CharField(max_length=50)
    lastname = models.CharField(max_length=50)
    birthdate = models.DateField()
    city = models.CharField(max_length=20, null=True, blank=True)
    def __str__(self):
        return self.lastname

def validate_numpages(value):
    if value < 50 or value > 1000:
        raise ValidationError('Numpages should between 50 and 1000')
class Book(models.Model):
    title = models.CharField(max_length=100)
    author = models.ForeignKey(Author)
    in_stock = models.BooleanField(default=True)

    numpages = models.IntegerField(null=True, blank=True, validators=[validate_numpages])
    def __str__(self):
        return self.title

class Student(User):
    PROVINCE_CHOICES = (
        ('AB','Alberta'), # First value is stored in db, the second is descriptive
        ('MB','Manitoba'),
        ('ON','Ontario'),
        ('QC','Quebec'),
    )
    # firstname = models.CharField(max_length=50, null=True, blank=True)
    # lastname = models.CharField(max_length=50, null=True, blank=True)
    address = models.CharField(max_length=100, null=True, blank=True)
    city = models.CharField(max_length=20, default='Windsor')
    province = models.CharField(max_length=2, choices=PROVINCE_CHOICES, default='ON')
    age = models.IntegerField(null=True, blank=True)
  #  photo = models.ImageField(null=True, blank=True, upload_to='photos')
    def __str__(self):
        return self.last_name

class Course(models.Model):
    course_no = models.IntegerField(primary_key=True)
    title = models.CharField(max_length=50)
    textbook = models.ForeignKey(Book, null=True, blank=True)
    students = models.ManyToManyField(Student, blank=True)
    def __str__(self):
        return str(self.course_no)+' '+ self.title

    # def __iter__(self):
    #     return self.title

class Topic(models.Model):
    subject = models.CharField(max_length=100, unique=True)
    intro_course = models.BooleanField(default=True)
    NO_PREFERENCE = 0
    MORNING = 1
    AFTERNOON = 2
    EVENING = 3
    TIME_CHOICES = (
        (0, 'No preference'),
        (1, 'Morning'),
        (2, 'Afernoon'),
        (3, 'Evening')
    )
    time = models.IntegerField(default=0, choices=TIME_CHOICES)
    num_responses = models.IntegerField(default=0)
    avg_age = models.IntegerField(default=20)
    def __str__(self):
        return self.subject

mysiteS171/myapp/forms.py
from django import forms
from myapp.models import Topic, Student
from django.contrib.auth.forms import UserCreationForm
class TopicForm(forms.ModelForm):
    class Meta:
        model=Topic
        fields=['subject','intro_course','time','avg_age']
        widget={'time':forms.RadioSelect()}
        label={'time':('Preferred Time'),'avg_age':('What is your age?'),'intro_course':('This should be an introductory level course')}


class InterestForm(forms.Form):
    interested = forms.ChoiceField(widget=forms.RadioSelect(), choices=((1, 'Yes'), (0, 'No')))
    age = forms.IntegerField(initial='20')
    comments = forms.CharField(required=False, widget=forms.Textarea, label='Additional Comments')

class StudentForm(forms.Form):
    class Meta:
        model = Student
        fields = ['first_name','last_name','address','city','province','age']
        PROVINCE_CHOICES = (
            ('AB', 'Alberta'),
            ('MB', 'Manitoba'),
            ('ON', 'Ontario'),
            ('QC', 'Quebec'),
        )
        province = forms.ChoiceField(widget=forms.RadioSelect(),choices=PROVINCE_CHOICES)

class RegisterForm(UserCreationForm):
    class Meta(UserCreationForm):
        model=Student
        fields=['username','first_name','last_name','email','address','city','province','age']

mysiteS171/myapp/views.py
from django.shortcuts import render,render_to_response
from myapp.models import Author,Book,Student,Course,Topic
from myapp.forms import TopicForm,InterestForm,StudentForm,RegisterForm
from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse
from django.views.generic import ListView, DetailView
from django.views import View
from django.shortcuts import render, get_object_or_404
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from datetime import datetime

# Create your views here.

# class IndexView(ListView):
#     model= Course
#     context_object_name='courselist'
#     template_name='myapp/index.html'

#class_based view

def IndexView(request):
     # def get(self, request):
        course_list = Course.objects.all()[:10]
        # register_form = RegisterForm()
        # Deal with cookies
        # if request.session.get('last_visit'):
        #     last_visit_time = request.session.get('last_visit')
        #     visits = request.session.get('visits', 0)
        #
        #     # Use seconds instead of days for testing
        #     if (datetime.now() - datetime.strptime(last_visit_time[:-7], "%Y-%m-%d %H:%M:%S")).seconds > 0:
        #         request.session['visits'] = visits + 1
        #         request.session['last_visit'] = str(datetime.now())
        # else:
        #     # this code was never reached, so the session was not being set
        #     request.session['last_visit'] = str(datetime.now())
        #     request.session['visits'] = 1
        #
        # if request.session.get('visits'):
        #     count = request.session.get('visits')
        # else:
        #     count = 0
        #
        # context = {
        #         'course_list':course_list,
        #         'count': count
        #
        #     }
        return render(request,'myapp/index.html',{'courselist':course_list})



def about(request):

    return render(request, 'myapp/about.html')

#def Coursedetail(DetailView):
#    model = Course
#    context_object_name = 'course'
#    template_name = 'myapp/detail.html'

#class_based view
def CourseDetailView(request, course_no):
# class CourseDetailView(View):
#     def get(self,request,course_no):
#         course=get_object_or_404(Course,course_no=course_no)
    course = Course.objects.get(course_no=course_no)
    return render(request, 'myapp/detail.html', {'course':course})

def base(request):
    return render_to_response('myapp/base.html',{'user':request.user})

def topics(request):
    topiclist = Topic.objects.all()[:10]
    return render(request,'myapp/topics.html',{'topiclist':topiclist})

def addtopic(request):
    topiclist = Topic.objects.all()
    if request.method == 'POST':
        form = TopicForm(request.POST)
        if form.is_valid():
            topic = form.save(commit=False)
            topic.num_responses = 1
            topic.save()
            return HttpResponseRedirect(reverse('myapp:topics'))
    else:
        form = TopicForm()
    return render(request, 'myapp/addtopic.html',{'form':form, 'topiclist':topiclist})

def topicdetail(request, topic_id):
    topic = Topic.objects.filter(id=topic_id)
    if request.method == 'POST':
        form = InterestForm(request.POST)
        if form.is_valid() and request.POST.get('interested') == '1':
            interested = form.cleaned_data['interested']
            age = form.cleaned_data['age']
            for t in topic:
                n = t.num_responses + 1
                topic.update(num_responses=n)
                a = (t.avg_age * t.num_responses + int(request.POST.get('age'))) / n
                topic.update(avg_age=a)
            return HttpResponseRedirect(reverse('myapp:topics'))
        else:
            return HttpResponseRedirect(reverse('myapp:topics'))
    elif request.method == 'GET':
        form = InterestForm()
    return render(request, 'myapp/topicdetail.html', {'form': form, 'topic': topic})

def register(request):
    studentlist = Student.objects.all()
    if request.method == 'POST':
        form = RegisterForm(request.POST,request.FILES)
        if form.is_valid():
            student = form.save(commit=False)
            student.save()
            return HttpResponseRedirect(reverse('myapp:index'))
    else:
        form = RegisterForm()
    return render(request, 'myapp/register.html',{'form':form, 'studentlist':studentlist})


def user_login(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('myapp:index'))
            else:
                return HttpResponse('Your account is disabled.')
        else:
            return HttpResponse('Invalid login details.')
    else:
        return render(request, 'myapp/login.html')

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse(('myapp:index')))

def mycourses(request):
    courses = Course.objects.filter(students__username=request.user.username)
    return render(request, 'myapp/mycourses.html', {'courses': courses})

mysiteS171/myapp/templates/myapp/about.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

mysiteS171/myapp/templates/myapp/about0.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>About Course</title>
</head>
<body>
    {% if courselist %}
        <h2>About Course Information</h2>
            <ul>
                {% for course in courselist %}
                    <li>{{ course.title }}{{ " is a important course !" }}</li>
                {% endfor %}
            </ul>

    {% else %}
        <strong>There are no course information!</strong>
    {% endif %}
</body>

<p><a href="/myapp/index0/">Index page</a> </p>
<p><a href="{% url 'myapp:index0' %}">Index page</a> </p>
</html>

mysiteS171/myapp/templates/myapp/addtopic.html
{% extends 'myapp/base.html' %}

{#{% block myhdg %}#}
{#    Hello USERNAME#}
{#{% endblock %}#}

{% block body_block %}
        <h2>You can add a new topic here.</h2>
        <form action="" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="submit" />
        </form>
{% endblock %}

mysiteS171/myapp/templates/myapp/base.html
<!DOCTYPE html>
{% load staticfiles %}

<html>
    <head>
         <meta charset="utf-8">

   <link rel="stylesheet" href="http://cdn.static.runoob.com/libs/bootstrap/3.3.7/css/bootstrap.min.css">
   <script src="http://cdn.static.runoob.com/libs/jquery/2.1.1/jquery.min.js"></script>
   <script src="http://cdn.static.runoob.com/libs/bootstrap/3.3.7/js/bootstrap.min.js"></script>
         <link rel="stylesheet" type="text/css" href="{% static 'myapp/style.css' %}" />
         <title>Course Listing APP - {% block title %}Welcome！{% endblock %}</title>
    </head>
    <body background="http://www.1tong.com/uploads/wallpaper/art/163-1-1920x1080.jpg">

<nav class="navbar navbar-inverse" role="navigation">
    <div class="container-fluid">
    <div class="navbar-header">
        <a class="navbar-brand" href="/myapp/index0/">Course Listing APP</a>
    </div>
    <div>
        <ul class="nav navbar-nav">
{#            <li class="active">#}
{#                <a href="/myapp/login/">Login</a></li>#}
            {% if request.user.is_authenticated %}
            <li><a href="/myapp/logout/">Logout</a></li>
            <li><a href="/myapp/mycourses/">Registered Course</a></li>
             {% else %}
            <li class="active">
                <a href="/myapp/login/">Login</a></li>
             <li><a href="/myapp/register/">Register</a></li>
        {% endif %}
            <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                    Topic
                    <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                    <li><a href="/myapp/topics/">List of Topics</a></li>
                    <li><a href="/myapp/addtopic/">Add a new Topic</a></li>
{#                    <li><a href="#">Jasper Report</a></li>#}
{#                    <li class="divider"></li>#}
{#                    <li><a href="#">分离的链接</a></li>#}
{#                    <li class="divider"></li>#}
{#                    <li><a href="#">另一个分离的链接</a></li>#}
                </ul>
            </li>
        </ul>
    </div>
    </div>
</nav>
        <div>

            {% block myhdg %}
                {% if request.user.is_authenticated %}
                    <h5>Hello {{ user.username }}</h5>
                {% else %}
                    <h5>  Hello USERNAME</h5>
                {% endif %}
            {% endblock %}

            {% block body_block %}
{#                <body background=""#}
                ***
            {% endblock %}

        </div>
        <hr />
        <div>
            <ul>
{#                <li class="hbar1"><a href="/myapp/about/">Find out about this site</a></li>#}
{#                <li class="hbar1"><a href="{% url 'myapp:index' %}">Click here to return to main page</a><br/></li>#}
{#                <li class="hbar1"><a href="/myapp/topics/">Topic</a></li>#}

{#                {% if request.user.is_authenticated %}#}
{#                    <li class="hbar1"><a href="/myapp/logout/">Logout</a></li>#}
{#                    <li class="hbar1"><a href="/myapp/mycourses/">Registered Courses</a></li>#}
{#                {% else %}#}
{#                    <li class="hbar1"><a href="/myapp/login/">Login</a></li>#}
{#                    <li class="hbar1"><a href="/myapp/register/">Register</a></li>#}
{#                {% endif %}#}

            </ul>
        </div>
    </body>
</html>

mysiteS171/myapp/templates/myapp/detail.html
{% extends 'myapp/base.html' %}

{#{% block myhdg %}#}
{#    Hello USERNAME#}
{#{% endblock %}#}

{% block body_block %}
    {% if course %}
        <h2>Course Detail Information</h2>
        <ul font="20px">
{#            {% for c in course %}#}
            <li>{{ "Course no: " }}{{ course.course_no }}</li>
            <li>{{ "Title: " }}{{ course.title }}
            <li>{{ "Textbook: " }}{{ course.textbook }}</li>
{#            {% endfor %}#}
        </ul>

    {% else %}
        <strong>There are no course detail information!</strong>
    {% endif %}
{% endblock %}

mysiteS171/myapp/templates/myapp/detail0.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Course Detail</title>
</head>

<body>
    {% if course %}
        <h2>Course Detail Information</h2>
        <ul>
            {% for c in course %}
                <li>{{ "Course no: " }}{{ c.course_no }}{{ "; Title: " }}{{ c.title }}{{ "; Textbook: " }}{{ c.textbook }}</li>
            {% endfor %}
        </ul>

    {% else %}
        <strong>There are no course detail information!</strong>
    {% endif %}
</body>

<p><a href="{% url 'myapp:index0' %}">Index page</a> </p>
</html>

mysiteS171/myapp/templates/myapp/index.html
{% extends 'myapp/base.html' %}

{#{% block myhdg %}#}
{#    <h5>Hello USERNAME</h5>#}
{#{% endblock %}#}

{% block body_block %}
    {% if courselist %}
        <h2>List of Courses</h2>
        <ul>
            {% for course in courselist %}
                <li><a href="{% url 'myapp:detail' course.course_no %}">{{ course.title }}</a></li>
            {% endfor %}
        </ul>

    {% else %}
        <strong>There are no available courses!</strong>
    {% endif %}
{% endblock %}

mysiteS171/myapp/templates/myapp/index0.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Course Listing APP</title>
</head>

<body>
    {% if courselist %}
        <h2>List of Courses</h2>
        <ul>
            {% for course in courselist %}
                <li><a href="{% url 'myapp:detail0' course.course_no %}">{{ course.title }}</a></li>
            {% endfor %}
        </ul>

    {% else %}
        <strong>There are no available courses!</strong>
    {% endif %}
</body>

<p><a href="{% url 'myapp:about0' %}">About page</a> </p>
</html>

mysiteS171/myapp/templates/myapp/login.html
{% extends 'myapp/base.html' %}

{% block body_block %}
        <h2>You can login here.</h2>
        <form action="" method="post">
            {% csrf_token %}
            <ul>
                 <li><label>User name:</label><input type="text" name="username"/></li>
                 <li><label>Password:</label><input type="password" name="password"/></li>
                 <li><input type="submit" value="login" /></li>
            </ul>
        </form>
{% endblock %}

mysiteS171/myapp/templates/myapp/logout.html
{% extends 'myapp/base.html' %}

{% block body_block %}
        <h2>Log out!</h2>

{% endblock %}

mysiteS171/myapp/templates/myapp/mycourses.html
{% extends 'myapp/base.html' %}

{% block body_block %}
    {% if request.user.is_authenticated %}
        {% if courses %}
          <h2>List of Courses</h2>
            <ul>
            {% for c in courses %}
                <li>{{ c.title }}</li>
            {% endfor %}
             </ul>
        {% else %}
             <p>You have not chosen any course yet!</p>
        {% endif %}
    {% else %}
        <strong>You are not a student. Please login!</strong>
    {% endif %}
{% endblock %}

mysiteS171/myapp/templates/myapp/register.html
{% extends 'myapp/base.html' %}

{% block body_block %}
        <h2>You can register as a new student here.</h2>
    <br>
        <form action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="submit" />
        </form>
{% endblock %}

mysiteS171/myapp/templates/myapp/topicdetail.html
{% extends 'myapp/base.html' %}


{% block body_block %}
    {% if topic %}
        <h2>Topic Detail Information</h2>
        <ul>
            {% for t in topic %}
                <li>{{ "Subject: " }}{{ t.subject }}{{ "; Num_responses: " }}{{ t.num_responses }}{{ "; Intro_course: " }}{{ t.intro_course }}{{ "; Avg_age: " }}{{ t.avg_age }}</li>
            {% endfor %}
        </ul>
    {% else %}
        <strong>There are no topic detail information!</strong>
    {% endif %}

    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="submit" />
    </form>
{% endblock %}

mysiteS171/myapp/templates/myapp/topics.html
{% extends 'myapp/base.html' %}

{#{% block myhdg %}#}
{#    Hello USERNAME#}
{#{% endblock %}#}

{% block body_block %}
    {% if topiclist %}
        <h2>List of Topics</h2>
        <ul>
            {% for topic in topiclist %}
                <li><a href="{% url 'myapp:topicdetail' topic.id %}">{{ topic.subject }}</a></li>
            {% endfor %}
        </ul>

    {% else %}
        <strong>There are no available topics!</strong>
    {% endif %}
{#    <ul class="nav nav-pills">#}
{#    <p>><a href="{% url 'myapp:addtopic' %}">Add a new topic</a> </p></ul>#}
{% endblock %}